import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { SiAffinitydesigner } from "react-icons/si";
import { AiFillHtml5 } from "react-icons/ai";
import { ImStatsBars } from "react-icons/im";
import { FaPhotoFilm } from "react-icons/fa6";
import { BiSolidEditAlt } from "react-icons/bi";
import { HiSpeakerphone } from "react-icons/hi";
import { BsFillDatabaseFill, BsWindowSidebar } from "react-icons/bs";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>PixelForge Solutions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logoshort.png" />
      </Head>

      {/* SCETION 1 */}

      <section className={styles.section1}>
        <img src="/scrolldown.svg" alt="" />
        <h2>
          Empowering Dreams, Crafting the Web <br />
          Your Vision, Our Code.
        </h2>
      </section>

      {/* SECTION 2 */}

      <section className={styles.section2}>
        <div className={styles.subsec1}>
          <div className={styles.textbox}>
            <img src="/qoutemark.svg" alt="" />
            <h3>
              We weave digital experiences that breathe life into brands,
              transform visions into code, and turn possibilities into
              captivating realities on the canvas of the internet.
            </h3>
            <hr className={styles.qoutehr} />
            <p>
              <span>Haider Irfan</span> <br />
              Executive Director
            </p>
          </div>
          <div className={styles.imagebox}>
            <img src="/mypic.jpg" alt="" />
          </div>
        </div>
      </section>

      {/* SECTION 3 */}

      <section className={styles.section3}>
        <h2>Our Services</h2>
        <div className={styles.subsec3}>
          <div className={styles.service}>
            <SiAffinitydesigner className={styles.design} />
            <h2>
              UI UX <br /> Design
            </h2>
            <p>
              As web designers, we create visually stunning and user-friendly
              websites that align with your brand and business goals. Our
              expertise includes responsive design for seamless experiences
              across all devices.
            </p>
          </div>
          <div className={styles.service}>
            <AiFillHtml5 className={styles.design} />
            <h2>Front End Development</h2>
            <p>
              As web designers, we create visually stunning and user-friendly
              websites that align with your brand and business goals. Our
              expertise includes responsive design for seamless experiences
              across all devices.
            </p>
          </div>
          <div className={styles.service}>
            <BsFillDatabaseFill className={styles.design} />
            <h2>Back End Development</h2>
            <p>
              As web designers, we create visually stunning and user-friendly
              websites that align with your brand and business goals. Our
              expertise includes responsive design for seamless experiences
              across all devices.
            </p>
          </div>
          <div className={styles.service}>
            <BsWindowSidebar className={styles.design} />
            <h2>Full Stack Development</h2>
            <p>
              As web designers, we create visually stunning and user-friendly
              websites that align with your brand and business goals. Our
              expertise includes responsive design for seamless experiences
              across all devices.
            </p>
          </div>
          <div className={styles.service}>
            <ImStatsBars className={styles.design} />
            <h2>Web App Development</h2>
            <p>
              As web designers, we create visually stunning and user-friendly
              websites that align with your brand and business goals. Our
              expertise includes responsive design for seamless experiences
              across all devices.
            </p>
          </div>
        </div>
      </section>

      {/* SECTION 4 */}

      <section className={styles.section4}>
        <div className={styles.subsec4}>
          <img src="/premierlogo.png" alt="" />
          <img src="/cubelogo.jpg" alt="" />
          <img src="/threadslogo.png" alt="" />
          <img src="/schoollogo.png" alt="" />
        </div>
      </section>

      {/* SECTION 5 */}

      <section className={styles.section5}>
        <h2>Our Work</h2>
        <div className={styles.subsec5}>
          <div className={styles.work}>
            <div className={styles.textbox2}>
              <h3>INDUSTRY:&nbsp;&nbsp;IT/Telecom</h3>
              <h2>Premier Solutions</h2>
              <p>
                <span>
                  “Premier Solutions” is a renowned Nation Wide and is proud to
                  present its integrated technology services and solutions as
                  well as its networking solutions in Pakistan. Over the time
                  the company has grown enormously providing state-of-the-art
                  solutions bringing the latest innovative technologies to its
                  client.
                </span>
                <br />
                <br />
                In our role as Web developers, we build & optimized this website
                by implementing server-side rendering for faster page loads,
                leveraging client-side routing for smooth navigation, and
                utilizing dynamic imports and code splitting for efficient
                resource loading. We integrated API routes for seamless data
                communication, while also employing static site generation to
                enhance performance and SEO.
              </p>
              <Link href={"https://www.premier-solution.net/"}>
                <button className={styles.visitbtn}>Vist Site</button>
              </Link>
            </div>
            <div className={styles.imagebox2}>
              <img src="/premsolweb.png" alt="" />
            </div>
          </div>

          <hr />

          <div className={styles.work}>
            <div className={styles.textbox2}>
              <h3>INDUSTRY:&nbsp;&nbsp;Portfolio</h3>
              <h2>PixelForge Solutions</h2>
              <p>
                <span>
                  I am a highly skilled web developer. Throughout my career, I
                  have acquired extensive expertise and hands-on experience in
                  the field of web development. I possess a deep understanding
                  of various programming languages, frameworks, and technologies
                  that are essential for creating dynamic and interactive
                  websites.
                </span>
                <br />
                <br />
                Our work as Next.js developers involved enhancing a website's
                performance and user experience. We utilized server-side
                rendering, client-side routing, dynamic imports, and code
                splitting to improve loading times and resource efficiency.
                Integration of API routes and static site generation further
                optimized data communication and overall performance.
              </p>
              <Link href={"https://haiderirfan.vercel.app/"}>
                <button className={styles.visitbtn}>Vist Site</button>
              </Link>
            </div>
            <div className={styles.imagebox2}>
              <img src="/pfsolweb.png" alt="" />
            </div>
          </div>

          <hr />

          <div className={styles.work}>
            <div className={styles.textbox2}>
              <h3>INDUSTRY:&nbsp;&nbsp;FinTech</h3>
              <h2>Technology Cube</h2>
              <p>
                <span>
                  At Technology Cube, we pride ourselves on our commitment to
                  professional ethics and technical competence. Our team of
                  young and energetic professionals is dedicated to providing
                  our clients with sincere and honest service that exceeds their
                  expectations. We believe in growth-oriented solutions that are
                  flexible enough to meet the unique needs of each
                  customer.sential for creating dynamic and interactive
                  websites.
                </span>
                <br />
                <br />
                We embarked on this journey by meticulously designing the
                website's architecture and layout, mapping out user flows and
                interactions. Our coding expertise came into play as we
                translated these designs into actual code, using a combination
                of HTML, CSS, and JavaScript. We ensured the website was
                responsive, adapting seamlessly to different screen sizes and
                devices.
              </p>
              <Link href={"http://technologycube.net/"}>
                <button className={styles.visitbtn}>Vist Site</button>
              </Link>
            </div>
            <div className={styles.imagebox2}>
              <img src="/cubeweb.png" alt="" />
            </div>
          </div>
        </div>
      </section>

      {/* SECTION 6 */}

      <section className={styles.section6}>
        <h2>
          What our <br /> Clients Say
        </h2>
        <div className={styles.subsec6}>
          <div className={styles.remark}>
            <img src="/premierlogo.png" alt="" /> <br />
            <div className={styles.qoutemark}>
              <img src="/qoutemarkblack.svg" alt="" />
            </div>
            <p>
              We are delighted with the outstanding work done by Pixel Forge
              Solutions. Their creativity, technical expertise, and attention to
              detail have elevated our website to new heights. They skillfully
              captured our brand's essence while ensuring a seamless user
              experience. The team's professionalism, efficient communication,
              and timely delivery exceeded our expectations.{" "}
            </p>
            <h4>
              <span>Irfan Elahi</span> <br />
              Proprietor @Premier Solutions
            </h4>
          </div>
          <div className={styles.remark}>
            <img src="/cubelogo.jpg" alt="" /> <br />
            <div className={styles.qoutemark}>
              <img src="/qoutemarkblack.svg" alt="" />
            </div>
            <p>
              We can't thank Pixel Forge Solutions enough for their
              remarkable work. Their team's design acumen and technical
              proficiency have given us a website that perfectly represents our
              brand. The collaboration was seamless, and they brilliantly
              incorporated our ideas while adding their creative touch. The
              website not only looks great but also functions flawlessly across
              all devices.
            </p>
            <h4>
              <span>Muhammad Ali</span> <br />
              Proprietor @TechnologyCube
            </h4>
          </div>
        </div>
      </section>
    </>
  );
}
